apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  LOCATION: {{ .Values.config.location | quote }}
  BACKEND_URL: {{ .Values.config.backendUrl | quote }}
