# Dev environment overrides for backend

# Image tag for dev
image:
  tag: "v1.3.0"

# Fewer replicas for dev
replicaCount: 1

# Lower resource limits for dev
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi
