{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "frontend-app.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "frontend-app.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
    namespace: {{ .Values.gateway.namespace }}
  hostnames:
  - {{ .Values.gateway.hostname | quote }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.routePath }}
{{- if not .Values.version.isDefault }}
      headers:
      - name: X-Version
        value: {{ .Values.version.name | quote }}
{{- end }}
    backendRefs:
    - name: {{ include "frontend-app.fullname" . }}
      port: {{ .Values.service.port }}
{{- end }}
